// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"af-go-frame"
	"af-goframe-demo/dddDemo/adapter/controller"
	"af-goframe-demo/dddDemo/infrastructure/conf"
)

// Injectors from wire.go:

func InitApp(server *conf.Server, data *conf.Data) (*af_go_frame.App, func(), error) {
	restServer := controller.NewHttpServer(server)
	app := newApp(restServer)
	return app, func() {
	}, nil
}
