// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"af-go-frame"
	"af-goframe-demo/dddDemo/adapter/controller"
	greeter2 "af-goframe-demo/dddDemo/adapter/controller/greeter"
	"af-goframe-demo/dddDemo/domain/greeter"
	"af-goframe-demo/dddDemo/infrastructure/conf"
	"af-goframe-demo/dddDemo/infrastructure/repository"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitApp(server *conf.Server, data *conf.Data, logger *zap.Logger) (*af_go_frame.App, func(), error) {
	greeterRepo := repository.NewGreeterRepo(data, logger)
	greeterUsecase := greeter.NewGreeterUsecase(greeterRepo, logger)
	greeterService := greeter2.NewGreeterService(greeterUsecase, logger)
	router := &controller.Router{
		GreeterApi: greeterService,
	}
	restServer := controller.NewHttpServer(server, router)
	app := newApp(restServer)
	return app, func() {
	}, nil
}
